// This file is generated by npm run generate-svg-sprite

export type IconName =
	| "chat-fill"
	| "compass"
	| "gear-fill"
	| "gift-fill"
	| "headphones"
	| "mic-fill"
	| "mic-mute"
	| "person-circle"
	| "person-fill-add"
	| "plus-circle-fill"
	| "plus-lg"
	| "search"
	| "shop"
	| "volume-up-fill";
